name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up OCaml and Opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5'

      - name: Install Dependencies
        run: |
          opam install . --deps-only --with-test

      - name: Build with Dune
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest

  lint-opam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - uses: ocaml/setup-ocaml/lint-opam@v3

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - uses: ocaml/setup-ocaml/lint-fmt@v3
